const getLocationList = (): string[] => [
  'Akaa',
  'Hämeenkyrö',
  'Ikaalinen',
  'Juupajoki',
  'Kangasala',
  'Kihniö',
  'Kuhmoinen',
  'Lempäälä',
  'Mänttä-Vilppula',
  'Nokia',
  'Orivesi',
  'Parkano',
  'Pirkkala',
  'Punkalaidun',
  'Pälkäne',
  'Ruovesi',
  'Sastamala',
  'Tampere',
  'Urjala',
  'Valkeakoski',
  'Virrat',
  'Vesilahti',
  'Ylöjärvi',
];

export { getLocationList };
